### ISSUE TITLE
:invalid_timezone when using Timex.parse/3 on a date string generated with Timex.format/3

### ISSUE THREAD

**Issue by marcelog** [bitwalker/timex#130]
Hello!

I've stumbled upon the following issue while upgrading from 1.0.0 to 2.0.0 and running my own tests that use randomly chosen timezones.

The issue in question is that when using `Timex.parse/3` to parse a string created by using `Timex.format/3` (and with some specific timezones), will yield an error because of it not recognizing the timezone string.

It seems to me that this operation should always succeed because it's just a reverse operation of the initial function call.

I'll try to describe the use case, perhaps I'm missing something.

Given this code:
```elixir
    tz_info = Timezone.get "Antarctica/McMurdo"
    datetime = DateTime.from_seconds 1457524752
    Timezone.convert datetime, tz_info
    {:ok, date_str} = Timex.format(
      Timezone.convert(datetime, tz_info), "%a, %d %b %Y %H:%M:%S %Z", :strftime
    )
    IO.puts "String: #{date_str}"
    Timex.parse date_str, "%a, %d %b %Y %H:%M:%S %Z", :strftime
```

And the following facts:
 * Timezone names are randomly chosen from the list obtained here https://github.com/bitwalker/timex/blob/2.0.0/priv/olson_to_win.exs#L204 (this is how I got to use such an uncommon timezone like **Antarctica/McMurdo**).
 * `date_str` ends up with the value `Thu, 10 Mar 2016 00:59:12 NZDT` (Note how the timezone name changed from `Antarctica/McMurdo` to `NZDT`, although it seems they are equivalent: http://www.timeanddate.com/worldclock/antarctica/mcmurdo).
 * The call to Timex.parse/3 succeeds but doesn't recognize the timezone NZDT, it yields:
```
{:ok,
 %Timex.DateTime{calendar: :gregorian, day: 10, hour: 0, millisecond: 0,
  minute: 59, month: 3, second: 12,
  timezone: {:error, {:invalid_timezone, "NZDT"}}, year: 2016}}
```

Am I missing something? Could this be a bug? Or perhaps an outdated timezone database somewhere? 

Any insights will be greatly appreciated :)

Thanks in advance!

**Comment by bitwalker** [comment]
The reason why this doesn't work is because parsing zone abbreviations is ambiguous, and so not supported. For instance, CST is a valid zone abbreviation in several places, each one with different semantics. NZDT is a valid zone in more than just the "Antarctica/McMurdo" locale, and so there is no way to parse the same zone from that string.

However there is a change I am going to make here, which is to change `%Z` to be the full timezone name for the strftime formatter/parser (because it is supported by the format spec). That way formatting/parsing of this string would be round-tripable.

I'll get a point release out sometime today :)

**Comment by marcelog** [comment]
Thanks for the quick reply! Understood, and it makes total sense.

One last (and hopefully not too dumb) question: Did this behavior change somehow in 2.0 (i.e: the string generated by %Z)? The code and the tests didn't change in essence, and the tests were run **tons** of times with 0.x and 1.x, throughout the last months, and this issue didn't manifest itself until now.

**Comment by bitwalker** [comment]
The behavior with what abbreviations are supported (I.e only POSIX zone names) changed in the last 1.x release. The previous behavior was actually broken, because the zone you got back for a given abbreviation may not have been the same one that generated it, resulting in incorrect behavior of that value was then manipulated in any way. This was actually documented but was a hack until I could write the POSIX zone parser which is used as a fallback if the zone isn't in the Olson database, for example, CST6CDT is a valid POSIX zone for American Central Standard Time.

Anyway, my point is that your tests may have passed but they were missing a much more insidious bug. In 2.0, timex is very strict about time and zones, but makes an effort to tell you what was bad, so if

**Comment by bitwalker** [comment]
Damn phone haha

What I was saying was if you are getting failed tests now, there is probably a real issue there rather than a timex bug per se, however please open issues so I can review and make sure, just like this one :)

I'm working on a comprehensive test suite right now so that I can make guarantees that a release is sound, but there are still gaps sadly.

**Comment by marcelog** [comment]
Gotcha :) Another timezone/locale :facepunch:!

So for completeness sake (and also in case you have any useful comments) I'll try to fully describe what we're doing.

* The users in our system are able to choose a timezone so they can receive events and generate reports in their own timezone.
* Both the tests and our users choose a timezone from this list https://github.com/bitwalker/timex/blob/2.0.0/priv/olson_to_win.exs. Our tests just pick one at random.
* We're testing that some events triggered in the system (and sent to our users) contain a property with a string formatted with the timezone of that user.
* In our system, we go from a unix timestamp to a string.
* In the test, we go back from the string to a timestamp, just to double check that the conversion went well. This is where the tests fail now when we pick up an ambiguous timezone.

Makes sense? I take it that If `%Z` will now yield the complete name instead of the abbreviations, we should be fine for the tests but also for the string we generate and send to our users. Do you have any suggestions?

Btw, no rush, take your time, and thank you very much for your time and this awesome lib :)

**Comment by bitwalker** [comment]
@marcelog You can use that `olson_to_win` list as a short list of zones, but to get the full list, you'll want to use `Timex.timezones/0` (this is coming in the release I'll be making here in an hour or so), which will feed you a list of all valid timezones in the Olson database. The list in that file is simply the map of Olson zones to timezones found in Windows, but is definitely not a complete list.

As far as the usage of `%Z`, you are exactly correct, your tests will pass, and the string sent to your users will be valid.

I'm spending extra time after the 2.0 release to work on tightening things up, so there are a few fixes and new features in 2.0.1 which I'm releasing today, so it's perfect timing :)

**Comment by marcelog** [comment]
Great, I look forward to the new release!

Thanks a lot for your help, I really appreciate it :)

**Comment by bitwalker** [comment]
@marcelog I just pushed 2.1.0 containing the changes above, plus a number of other things, take a look at the changelog if you're interested in what those all are, let me know if you run into any issues and I'll take a look right away.

**Comment by marcelog** [comment]
That's great @bitwalker, thanks for the heads up! I will be able to look at this later this evening, in about 2-3 hours, so I will definitely let you know of any comments I might have. 

Best! :)

**Comment by marcelog** [comment]
Everything looks great so far, great release! Thanks!

**Comment by bitwalker** [comment]
@marcelog That's great to hear :), ping me if you spot anything!
