### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by benwilson512** [bitwalker/timex#168]
Hey!

After running into some issues with the performance of TimexEcto (documented here: https://github.com/bitwalker/timex_ecto/issues/26) I thought I would do some overall profiling and created

https://github.com/benwilson512/time-bench

TL;DR:

# TimeBench
## DateTimeFormatBench
```
Calendar.DateTime.Format.rfc3339                200000   7.76 µs/op
Timex.format!(@timex_iso_z, {ISOz})              10000   213.17 µs/op
```
## DateTimeParseBench
```
Calendar.DateTime.from_erl! @erl                100000   11.34 µs/op
Calendar.DateTime.Parse.rfc3339_utc @iso_z       50000   30.20 µs/op
Timex.DateTime.from @erl                         20000   78.80 µs/op
Timex.parse! @iso_z                              20000   86.77 µs/op
```
## EctoDumpBench
```
Ecto.DateTime.dump(@iso_z)                   100000000   0.08 µs/op
Calecto.DateTimeUTC.dump(@iso_z)              10000000   0.18 µs/op
Timex.Ecto.DateTime.dump(@iso_z)                 10000   117.86 µs/op
```
## EctoLoadBench
```
Calecto.DateTimeUTC.load(@erl)                10000000   0.13 µs/op
Ecto.DateTime.load(@erl)                      10000000   0.13 µs/op
Timex.Ecto.DateTime.load(@erl)                   20000   74.96 µs/op
```
## ErlToIsoZBench
```
custom                                        10000000   0.58 µs/op
Calendar                                        100000   18.56 µs/op
Timex                                            10000   280.32 µs/op
```

Obviously most of the issues with Timex.Ecto is that it's simply not taking short cuts available to it. However, parsing erl times is still 7x slower, and ordinary ISOz times are almost  3x slower.

The Timex.Ecto stuff though is the most problematic. I discovered the issue when in production decoding a mere 1500 records produced decode times of over 400ms.

**Comment by bitwalker** [comment]
One of the problems here is that you are not calling equivalent functions between Calendar and Timex. For example, `Timex.from` runs through a protocol, and has to pattern match to determine what type of input value it's dealing with. The direct equivalent to the Calendar function called is `Timex.DateTime.from_erl`. 

Likewise, RFC-3339 and ISO-8601 are not identical, Timex exposes an `{RFC3339z}` token specifically for that format. In general though I would expect Timex parsing to not be as fast as a handrolled parser, since it parses a much wider array of formats, and does so using parser combinators, which are never quite as performant - that said, the difference in practice should be fairly minimal.

I'll run the same benchmarks and report back with specifics. I'm going to address your timex_ecto issue though, since that does seem like an easy win.

Thanks for all the work on this!

**Comment by bitwalker** [comment]
Closing this since it's open in timex_ecto already, and has been addressed across the past few releases. I'll keep tweaking things as well :)
