### ISSUE TITLE
to_unix truncates seconds

### ISSUE THREAD

**Issue by baron** [bitwalker/timex#201]
I noticed that the replacement methods for the old "to_second" function seems to truncate the DateTime to seconds.

I'm not sure this is desirable default behavior since there is some loss of data and no fine-grained control for the developer.

### Steps to reproduce

- API function called
- Arguments provided

 Timex.now |> Timex.to_unix
 1469770928

In Timex 2.x it used to be:

use Timex
Time.now |> Time.to_seconds
1469771537.370013

### Description of issue

- What are the expected results?
option to not truncate timestamps by default?

to_unix doesn't have a counterpart to to_gregorian_milliseconds

it also doesn't match Elixir's default behavior with DateTime.to_unix

DateTime.to_unix(Timex.now, :microseconds)
1469780610645441

- If you are certain this is a bug in Timex, do you have references I
  can use to check the algorithm/logic against? For instance, a well-established
  date/time library in another language, a paper, test suite, etc. It is by no
  means a requirement, but is immensely helpful in fixing bugs, and provides me
  extra data to use when building out the test suite

**Comment by bitwalker** [comment]
UNIX timestamps are always in seconds since the epoch, with no further precision. If you require high precision, you can use `Timex.to_gregorian_microseconds(datetime) - Timex.to_unix(Timex.epoch)`, which will give you microseconds since the epoch.

However, adding an overload to `to_unix` which takes precision as an argument, to simplify this use case, is a good idea so that's something I'll add to my TODO list.
