### ISSUE TITLE
Parsing of weeks failed

### ISSUE THREAD

**Issue by pollingj** [bitwalker/timex#243]
### Steps to reproduce

This is a failing test

```   
  test "parse format with weeks of year" do
    assert {:ok, _date} = parse("2017-42", "%Y-%W")
  end
```
### Description of issue

The above test fails with {:error, "Unrecognized token: week_of_year"}
I'm fairly new to Elixir, and I'm not clear on the DateTime stuff.  Any pointers at all?  I'm happy to try and fix, just need some pointers :)

**Comment by leobessa** [comment]
I've got the same issue. I tried to fix it but I got confused about the expected output.

First I added the following code to `update_date`.

```elixir
defmodule Timex.Parse.DateTime.Parser do
    defp update_date(%DateTime{year: year, hour: hh} = date, token, value, tokenizer) when is_atom(token) do
    case token do
    # ... weeks (add this clause)
    :week_of_year ->
        %Date{year: y, month: m, day: d} = Timex.from_iso_triplet({year, value, 1})
        %{date | :year => y, :month => m, :day => d}
    end
  end
end
```

Note that we are assuming the weekday is 1 (Monday) on `Timex.from_iso_triplet({year, value, 1})`.

And then I wrote the test, and it passed:

```elixir
test "parse ISOweek" do
    assert ~N[2016-11-28 00:00:00] = Timex.parse!("2016-W48", "{ISOweek}")
    assert ~N[2009-12-28 00:00:00] = Timex.parse!("2009-W53", "{ISOweek}")
    assert ~N[2007-11-19 00:00:00] = Timex.parse!("2007-W47", "{ISOweek}")
end
```

I'm not confident about the results because `2016-W48` is not a date, it's a week.

What would be the expected result if we follow the principle of least surprise?
- NaiveDateTime
  - on Monday
  - on Sunday
  - Sunday if %U is used, and Monday if %W is used
- AmbiguousDateTime (what should be assigned to :before and :after ?)
- DateTime (if timezone is provided)

---
I'm also confused about the nomenclature used on directives: `iso_weeknum` and `week_of_year`. Why they have different names?

**Comment by bitwalker** [comment]
I've addressed this in master, it will go out in the next release. Thanks for the detailed report!
