### ISSUE TITLE
DateTime Microsecond precision ignored for 0 value when formatting as {ISO:Extended}

### ISSUE THREAD

**Issue by mbuhot** [bitwalker/timex#248]
### Steps to reproduce

```Elixir
{{2016,1,1},{12,23,34}}
|> Timex.to_datetime 
|> Timex.set(microsecond: {0, 3})
|> Timex.format!("{ISO:Extended}")

"2016-01-01T12:23:34+00:00" # <--- 34 seconds
```

vs Elixirs `DateTime.to_iso8601`

```Elixir
{{2016,1,1},{12,23,34}}
|> Timex.to_datetime 
|> Timex.set(microsecond: {0, 3})
|> DateTime.to_iso8601

"2016-01-01T12:23:34.000Z" # <--- 34.000 seconds
```

### Description of issue

When `Timex.format!("{ISO:Extended}")` is used to format the datetime, the fractional seconds component is omitted if the value of microseconds is 0.

The equivalent function in the elixir standard library always respects the digits of precision component of the `:microsecond` field when formatting, even if the value is 0 microseconds.

This caused an issue with a downstream system that was assuming a fractional second component would always be present in the formatted DateTime values that were output using `Timex.format`.

**Comment by bitwalker** [comment]
I'm fine with changing things to be consistent with the standard library here, but the ISO-8601 spec is pretty clear that the two are equivalent. If a system is choking on one but not the other, then it is not using a ISO-8601-compatible parser, which is fine, but dangerous to be sure for the reason you discovered. I'll update this once the fix is upstream.

**Comment by mbuhot** [comment]
Thanks @bitwalker!
