### ISSUE TITLE
OpenVPN status log date format

### ISSUE THREAD

**Issue by renato** [bitwalker/timex#263]
### Steps to reproduce

- Timex.parse/2
- `"Sat Jan  7 13:16:53 2017", "{WDshort} {Mshort} {D} {h24}:{m}:{s} {YYYY}"`

### Description of issue

- GitHub strips it, but there's a double whitespace between Jan and 7, because 7 is < 10. In a date like `Tue Jan 10 16:14:06 2017`, however, there's only one space between Jan and 10. I don't know if this is from any default, but OpenVPN status uses this format. I tried with some other format alternatives but I couldn't make it parse it correctly, so I'm currently stripping the double space before parsing.

- I'm not certain this is a bug (it's possible there's some alternative parsing string I'm missing), but I saw a example code in PHP that uses `strtotime()` to parse the same string.

**Comment by bitwalker** [comment]
You want `{WDshort} {Mshort} {_D} {h24}:{m}:{s} {YYYY}`. The `_` modifier to the `D` token tells it to format with spaces as padding (and to likewise expected space-padded digits when less than 10). The default padding is zeroes (which can be explicitly set with `0` instead of `_` as the modifier). Hope that helps!

**Comment by renato** [comment]
Thanks, that helped a lot!

I missed it in the docs when trying to solve it as it's deep in Timex.Format.DateTime.Formatters.Default, I'm sorry. :)
