### ISSUE TITLE
Document tzdata's auto-update behavior

### ISSUE THREAD

**Issue by cdegroot** [bitwalker/timex#284]
I discovered that this library includes tzdata, which auto-updates time zone data. While admirable to have a library that tries to stay up-to-date, in the past using libraries that tried to pull data from production has for me invariably ended up in tears. There are security and stability issues around having more code than you bargained for being active on production systems.

The author of tzdata takes the position that having up-to-date TZ data is more important than the potential downsides; for direct users of the library that's arguable as someone who directly uses it apparently has an interest in TZ calculations (I'd still disable it) and the author documented how to disable it. I failed to persuade it to make not updating the - IMO safe - default (https://github.com/lau/tzdata/issues/29). 

Would a prominent mention of this behavior in the README be a PR that you'd consider merging in? I'm not sure whether timex could default-disable this, so this is the best I can come up with :)

**Comment by bitwalker** [comment]
I would be happy to merge something in the docs and README about this behaviour and how to disable it, but I would also like to make sure the note does not actively discourage users from using the default behaviour. I agree with @lau that correct tzdata is the entire point of such a package and that unless you have specific requirements which force you to manually perform such updates, you should stick to the defaults. The `tzdata` package has been around for a long time now, and having managed many production Elixir applications at this point, it's never been a problem in my experience. That's not to say it can't be, but the track record has been a good one up to this point.

**Comment by cdegroot** [comment]
I find it, err,  "interesting" to see so much support for behaviour I've always worked hard to discourage and/or disable. I guess my views on what's required as a baseline for secure software are probably a tad on the strict side, but I'll submit a neutrally worded PR to the README.

**Comment by bitwalker** [comment]
I definitely understand the security concerns, and it's one of the reasons an option exists to disable it in the first place. The reason why we recommend this as the default behaviour is because inaccurate timezone information is worse than no timezone information at all - if you are operating on DateTimes and have updates disabled, then unless you have an alternative method in place to keep up on tzdata releases and ensure they are installed before their changes take effect (across all your systems), you will end up with incorrect/invalid data. I also think the security risk here is very minimal due to how the data fetched from IANA is handled, but the process would need to be audited to know for sure.
