### ISSUE TITLE
Day missing in RFC822 conversion

### ISSUE THREAD

**Issue by suhrawardi** [bitwalker/timex#289]
Hi,

Seems like the `RFC822` conversion is going wrong, and other `DAY` formatting as well:

### Steps to reproduce

```
iex(1)> {:ok, datetime} = Ecto.DateTime.cast("2017-03-01 18:30:21")
{:ok, #Ecto.DateTime<2017-03-01 18:30:21>}
iex(2)> datetime |> Timex.format("{RFC822}")                       
{:ok, ", 01 Mar 17 18:00:00 "}
iex(3)> datetime |> Timex.format("{WDmon}")                        
{:error, :invalid_date}
iex(4)> datetime |> Timex.format("{WDsun}")
{:error, :invalid_date}
iex(5)> datetime |> Timex.format("{WDshort}")
{:error, :badarg}
iex(6)> datetime |> Timex.format("{WDfull}") 
{:error, :badarg}
```

### Description of issue

- What are the expected results?
I expected it to return `{:ok, "Wed, 01 Mar 17 18:00:00 "}`

Thanks a lot!

**Comment by bitwalker** [comment]
This is due to using `Ecto.DateTime`, which is missing some key fields. You should convert the `Ecto.DateTime` to an Elixir `DateTime` or `NaiveDateTime`, or convert it to an Erlang datetime tuple and pass that to Timex. Currently, Timex doesn't support the legacy Ecto structs, which are going away in favor of Elixir calendar types in the next release as far as I'm aware.

**Comment by suhrawardi** [comment]
Thanks @bitwalker !
