### ISSUE TITLE
Unable to parse RFC2822 Dates

### ISSUE THREAD

**Issue by yasserhussain1110** [bitwalker/timex#299]
#### Timex Version used - 
  3.1.13

#### Steps to reproduce

I ran
```ex
Timex.Parse.DateTime.Parser.parse("January 1, 1970", "{RFC2822}")
```
and got
```ex
{:error, "Expected at least one parser to succeed at line 1, column 0."}
```

Why am I not able to parse **RFC2822** type date strings?
Is there any other way to parse such dates?

I am trying to find an equivalent code for Javascript's `Date.parse`. For example - 
```js
Date.parse("January 1, 1970")
```
returns a timestamp.

How do I implement this?
Please help.

**Comment by yasserhussain1110** [comment]
Closing this issue as I found a workaround.
```ex
Timex.Parse.DateTime.Parser.parse("January 1, 1970", "{Mfull} {D}, {YYYY}")
```

**Comment by bitwalker** [comment]
Reopening this, as it's a bug. I'll get this patched today and push a new release.

**Comment by bitwalker** [comment]
Wait, I just noticed that date/time string you are providing isn't an RFC 2822 date/time, as defined [here](https://www.ietf.org/rfc/rfc2822.txt). Also, I don't have a specific parser for RFC 2822, but I do for RFC 822, and from my reading, the formats appear to be identical, so you could give `{RFC822}` a try instead.

I did just push a fix to prevent requiring the weekday abbreviation, as that's optional, but the parser was requiring it.

**Comment by yasserhussain1110** [comment]
Tried running this code - 
```ex
Timex.parse("December 15, 2015", "{RFC822}")
```
Got - 
```ex
{:error, "Expected `weekday abbreviation` at line 1, column 1."}
```

You are right, my mistake. The date wan't in RFC2822 format.  

But then again `"January 1, 1970"` format is pretty common format specially for people coming from Javascript background.
 
So maybe if Timex had a function for parsing that kind of dates, it would be much appreciated.  

But this is just what I thought. I don't know if other people have faced similar problems. Thanks. :)

**Comment by bitwalker** [comment]
I agree that it's pretty common, unfortunately there is no specification for dates of that format, which is where I draw the line. I prefer to only add commonly-used formats as shortcut tokens in Timex's formatting tokenizer - for date/times such as the one you've shown here, the format string is short enough, that it's exactly the kind of thing those format strings are intended for, it's also more readable to be able to see the format, instead of something like `{MDY}` - the shortcut tokens should only be for things which are so common that you don't need to see the full format to know what is expected and/or are complicated enough that not providing them out of the box would be likely to cause compatibility issues.

**Comment by yasserhussain1110** [comment]
I am happy to use format string. Thanks.

**Comment by darraghenright** [comment]
Hi 👋 

Sorry to necro this issue! Might be helpful for others. I wanted to parse the `Date` header from an RFC2822 email — the RFC822 version doesn't work because it only allows two digit years. There are a few other differences around zones as well, RFC2822 is just stricter as it only allows time offsets, not other stuff like timezone abbreviations etc.

So using `{RFC822}` doesn't work — this error refers to the second `2` in the year:

```elixir
iex(1)> Timex.parse("Thu, 25 Jul 2024 23:59:20 +0100", "{RFC822}")
{:error, "Expected space but found `2` at line 1, column 15."}
```

This should work for RFC2822 dates:

```elixir
iex(1)> Timex.parse("Thu, 25 Jul 2024 23:59:20 +0100", "{WDshort}, {D} {Mshort} {YYYY} {h24}:{m}:{s} {Z}")
{:ok, #DateTime<2024-07-25 23:59:20+01:00 +01 Etc/UTC+1>}
```
