### ISSUE TITLE
Timex.diff returning wrong amount of years between two dates?

### ISSUE THREAD

**Issue by richeterre** [bitwalker/timex#317]
### Steps to reproduce

```
$ iex -S mix

iex(1)> Timex.diff(~D[2000-12-26], ~D[2000-01-01], :years)
1
```

### Description of issue

The returned result is `1`, but I'd expect this to return `0` as no full year has passed between the two dates. (The use case is to calculate a user's displayed age based on their birthdate.)

As I'm quite an Elixir beginner, might I be missing something crucial here? 😯

**Comment by bitwalker** [comment]
I'll move my Twitter replies here for posterity :)

The date range you provided is 12 months, and the diff implementation for years currently just looks at the number of months divided by 12. I'm open to suggestions on improving this at the moment, but it's a non-trivial problem, as "years" is not a constant time unit. Measuring years as divisions of 365 days would probably be more accurate, and I'm fine with making that change, but it still has the potential to report incorrect numbers due to leap years.

**Comment by bitwalker** [comment]
For your specific use case, `Timex.diff(Timex.today, birthday, :days) |> div(365)` would probably be accurate enough. One option we have is to start at `birthday` and walk forward and count the number of occurrences of that month/day. Now that intervals are baked in to Timex, I should probably update the diffing algorithm to leverage that capability.
