### ISSUE TITLE
ISO:Extended parser does not handle date/time without TZ info

### ISSUE THREAD

**Issue by mspanc** [bitwalker/timex#318]
### Steps to reproduce

```elixir
Timex.parse("1985-04-12T10:15:30", "{ISO:Extended}")
{:error, "Expected either Z or a valid timezone offset, but got ``"}
```

### Description of issue

ISO8601 allows to specify date/time without timezone specifier (see section 4.3.2 of ISO8601 spec) but they are not parsed correctly as local time by Timex.parse.

See examples in section 4.3.2: http://www.uai.cl/images/sitio/biblioteca/citas/ISO_8601_2004en.pdf
 
It should either return local time or have additional argument for passing desired time zone.

Using 3.1.17.

**Comment by kaelumania** [comment]
Further I found that the result of `Timex.parse!("2017-06-27T08:32:55.8000011Z", "{ISO:Extended}")` can not be inspected (receiving an argument error). Note: This happens after the 6th digit of the subseconds. Furthermore, when I try to `Poison.encode!` this string it raises an error 
```
** (ArgumentError) argument error
             :erlang.binary_part("000000", 0, 7)
    (elixir) lib/calendar/iso.ex:148: Calendar.ISO.time_to_string/4
    (elixir) lib/calendar/iso.ex:207: Calendar.ISO.datetime_to_iso8601/11
    (poison) lib/poison/encoder.ex:345: Poison.Encoder.DateTime.encode/2
    (poison) lib/poison.ex:41: Poison.encode!/2
```

**Comment by bitwalker** [comment]
Thanks for the report!

Regarding the OP issue, I will modify the parser to return a NaiveDateTime if the timezone specifier is missing.

Regarding @kaelumania's issue, that is a problem with the Elixir standard library types, and should be reported to the elixir-lang tracker.

**Comment by bitwalker** [comment]
I just published 3.1.18 which fixes this issue.

**Comment by kaelumania** [comment]
@bitwalker I think there is an issue with `Timex` too.

1. With precision more than 6 the `sec_fractional` are `0`
```elixir
$ Combine.parse("2017-06-27T08:32:55.80011111123333Z", Timex.Parse.DateTime.Parsers.ISO8601Extended.parse)

[[year4: 2017, month: 6, day: 27, hour24: 8, min: 32, sec: 55,
  sec_fractional: {0, 14}, zname: "Etc/UTC"]]
```

2. When converting to Elixir DateTime the `sec_fractional` is not being truncated, but `elixir` only supports 6
```elixir
$ {:ok, d} = Timex.Parse.DateTime.Parser.parse("2017-06-27T08:32:55.80011111123333Z", "{ISO:Extended}")

$ d.microsecond
{0, 14}
```
> this in turn results in an Error when trying to convert the `DateTime` to a String, see  https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/calendar/iso.ex#L231

**Comment by bitwalker** [comment]
Ah I see, I'll ensure that the parser caps the precision at 6 and add some tests for the roundtrip. Thanks for reporting that!

**Comment by kaelumania** [comment]
Yeah, I would say the parser can return more that 6 digits, but the conversion to the standard elixir datetime struct should truncate at 6. iso8601 allows more than 6 digits therefore I would prefer the parser to parse all digits and the in to_datetime truncate.

**Comment by bitwalker** [comment]
If the standard library API enforces a precision of <= 6, then we can't allow the parser to set a precision greater than that or we risk operations using the standard library failing because an invariant has been broken. Additionally, internally we assume that the greatest precision we can work with is microseconds, which would cause various date/time arithmetic to fail if the value of microseconds is higher than the precision allows. This also applies to integration with other libraries which may expect a precision of microseconds, such as Ecto.

I've just pushed a fix though that will truncate the fractional value at 6 digits - it does mean that extra precision is lost, but unfortunately that's unavoidable at this point in time. I would love to support nanosecond precision in Timex, but it would break compatibility with the standard library, at which point it's usefulness diminishes greatly. We should probably try and push for nanosecond precision in Elixir's standard library, once it's supported there, I will gladly ensure Timex supports it as well.

**Comment by mspanc** [comment]
I totally agree with @bitwalker. Is there any upstream issue in Elixir core or should I create one?

**Comment by kaelumania** [comment]
@mspanc there is only this [discussion](https://github.com/elixir-lang/elixir/issues/4681#issuecomment-311587964). But Jose add some guards to `Time.new` (https://github.com/elixir-lang/elixir/blob/5fc7ee129ddfe534cdc6d9b1e2b5eb90b698c811/lib/elixir/lib/calendar/iso.ex#L277)

**Comment by mspanc** [comment]
elixir-lang/elixir#6299 was refused, so I think it has to remain like it is with cutting precision to 6.
