### ISSUE TITLE
Some Date.* functions require updating after recent fixes

### ISSUE THREAD

**Issue by bitwalker** [bitwalker/timex#33]
`Date.shift`, `Date.compare`, and `Date.diff` all require review/rework after #32 was merged. Review the PR and #24 for details.

/cc @bbense

**Comment by bbense** [comment]
Actually, the PR for #24 include changes to Date.compare and Date.shift,
based on the fixing the bug in Date.to_secs.

These changes pass all the current tests.

**Comment by bitwalker** [comment]
So just `Date.diff` requires review?

**Comment by bbense** [comment]
Sorry, I'm being a bit sloppy with my language and it's causing confusion.

As far as I know, there are no functions that need reworking currently.
Changing Date.to_secs to correctly
account for timezone caused both Date.compare and Date.shift to need
reworking since they "relied"
on the incorrect behavoir of Date.to_secs. These functions now pass all
current tests.

I misread my patch, I did not require any changes to Date.diff.

I did a quick overview of all other uses of Date.to_secs in the library and
did not find any issues. The code currently
passes all the tests.

However, it would probably be a good idea for someone to double check the
other uses of Date.to_secs
in the code to make sure there are no issues that aren't covered by the
current test suite.

- Booker C. Bense

**Comment by bbense** [comment]
On thing I noticed is that many of the tests do not have versions with timezones other than utc. I think the best way forward would be to add timezone version tests of all the Date functions.

**Comment by bitwalker** [comment]
Excellent point. So to amend the TODO for this, we probably just need to review usages to ensure it's being used properly. I would guess it's entirely possible the test coverage misses some gaps, but we'll have to probably wait for bug reports before we know what those are (if they are present).
