### ISSUE TITLE
Minutes and seconds are always rendered as "00"

### ISSUE THREAD

**Issue by Pacodastre** [bitwalker/timex#335]
### Steps to reproduce

    iex(1)> Ecto.DateTime.utc() |> Timex.format!("{h24}:{m}")
    "11:00"
    iex(2)> Ecto.DateTime.utc() |> Timex.format!("%H:%M:%S", :strftime)
    "11:00:00"
    iex(3)> Ecto.DateTime.utc() |> Timex.format!("%R", :strftime)      
    "11:00"

### Description of issue

- What are the expected results?

`Timex.format!` always returns `00` for both the seconds and the minutes, whatever time it is. It should return the actual number of minutes and seconds.

- If you are certain this is a bug in Timex, do you have references I
  can use to check the algorithm/logic against? For instance, a well-established
  date/time library in another language, a paper, test suite, etc. It is by no
  means a requirement, but is immensely helpful in fixing bugs, and provides me
  extra data to use when building out the test suite

Bash:

    date --utc +%H:%M:%S
    11:04:57

**Comment by alvinlindstam** [comment]
The issue seems to be that the formatter does not convert the Ecto.DateTime struct to a supported format before sending it to the formatting function. Ecto.DateTime structs keep the seconds and minutes with different keys than Elixir.DateTime structs (which is what the formatter expects).

I'll submit a PR. In the meantime, explicitly converting the Ecto.DateTime using Timex.to_naive_datetime before formatting is a possible workaround.

**Comment by bitwalker** [comment]
I'll push a new release today. Thanks for reporting, and thanks to @alvinlindstam for the fix!

**Comment by Pacodastre** [comment]
Thanks for fixing it, and for the work around.
