### ISSUE TITLE
Implement Timex.Comparable for times

### ISSUE THREAD

**Issue by TBK145** [bitwalker/timex#339]
I think it would be very useful for Timex to be able to compare times and we can give Time structs as arguments to functions like `between?`, `after?` and `before?`.

**Comment by bitwalker** [comment]
Hmm, I suppose my question here would be what are the semantics if you compare a `Time` and a `DateTime`? There is no timezone information associated with a `Time`, so you can't know that the time contained in the `DateTime` is in the same timezone, and thus be able to reason about comparisons. I know it's a pathological case (why would anyone compare those two things), but that's part of how the `Comparable` protocol works - it knows that it can resolve the inputs to the same timezone and thus do comparisons correctly. One option would be to add clauses to `Timex.before?` and friends to handle `Time` directly rather than going through the protocol, and only allow comparisons when all of the inputs are `Time` structs - I'm open to that.

**Comment by TBK145** [comment]
I was thinking about that as well, but figured that `Time` would never contain a timezone anyway, I never took `DateTime`s into account.
Would it be an option to only compare structs without timezones and structs that both have timezones, and return an error when only one of both has a timezone?

**Comment by alvinlindstam** [comment]
But Timex supports comparing datetimes with and without timezones today, right? By assuming utc?

```
iex> Timex.compare(Timex.now(), Timex.now() |> Timex.to_naive_datetime())
-1
```

However, my other concern would be the semantics when comparing times to datetimes (naive or not). Should `~N[2000-00-00 20:00:00.000]` compare before or after `~T[10:00:00.000]`? Only comparing times to other times seems reasonable, but then what is the upside of using Timex.compare instead of Time.compare?

**Comment by bitwalker** [comment]
> Would it be an option to only compare structs without timezones and structs that both have timezones, and return an error when only one of both has a timezone?

It is something I'm considering, see my notes on such comparisons below.

> But Timex supports comparing datetimes with and without timezones today, right? By assuming utc?

It's probably more accurate to say that we don't assume UTC so much as we apply no timezone rules whatsoever to `NaiveDateTime` or `Date` - but one could make the argument that by converting either of them to the number of gregorian microseconds they represent, that we are implicitly assuming UTC for those inputs, and I won't argue that. For timezone-aware inputs, we first shift those values to UTC properly, then do comparisons. I do think it may be worth restricting the protocol implementations such that you can't compare a timezone-aware date/time against one which is not timezone-aware - just to make it explicit that there is ambiguity there that can't be precisely resolved - but I suspect in practice it's rare that those kind of comparisons are being made.

> However, my other concern would be the semantics when comparing times to datetimes (naive or not). Should ~N[2000-00-00 20:00:00.000] compare before or after ~T[10:00:00.000]? Only comparing times to other times seems reasonable, but then what is the upside of using Timex.compare instead of Time.compare?

We could compare just the Time element of the `DateTime`/`NaiveDateTime` in the protocol implementations, assuming that the `Time` is in the same timezone and on the same day - but that has implications as well, as you could create a `Time` which on a given day and zone doesn't actually exist.

My suggestion is that if `Time.compare` is not satisfactory for the use case here, that we constrain the comparison of `Time` such that only two `Time` structs may be compared - and to do so without going through the comparable protocol. It's not ambiguous and we don't have to try and account for weird edge cases.
