### ISSUE TITLE
Granularity in compare and equal?

### ISSUE THREAD

**Issue by dmarkow** [bitwalker/timex#348]
### Steps to reproduce

```elixir
Timex.equal? ~D[2017-07-27], ~D[2017-07-28], :months
# => true
Timex.equal? ~D[2017-07-27], ~D[2017-08-01], :months
# => true
Timex.equal? ~D[2017-07-27], ~D[2017-08-26], :months
# => true
Timex.equal? ~D[2017-07-27], ~D[2017-08-27], :months
# => false
```

### Description of issue

I only expected the first statement above to return true, however the 2nd/3rd also returned true. My assumption was the granularity above would be used to truncate the two dates and see if they were in the same calendar month. But instead, it's being treated as  "is it within a month?" 

Is this by design? The documentation doesn't appear to specify exactly how the granularity is used, and other date/time libraries I've used (e.g. [Moment.js's isSame()](http://momentjs.com/docs/#/query/is-same/) on the frontend or using [date_trunc in Postgres](https://www.postgresql.org/docs/9.1/static/functions-datetime.html#FUNCTIONS-DATETIME-TRUNC)) would count all three August comparisons above as false

**Comment by bitwalker** [comment]
Yes this is intentional - comparisons are performed based on the difference between the two values, and granularity affects the interpretation of the difference. Put more simply, if the granularity unit, e.g. `:months` is larger than the difference between the two values, then they are effectively equal for that comparison.
