### ISSUE TITLE
Performance of shifting datetimes

### ISSUE THREAD

**Issue by doughsay** [bitwalker/timex#357]
Forgive me if I'm comparing apples to oranges here, but I've noticed a significant difference in the performance of shifting dates between Timex and ActiveSupport datetimes in Ruby.

A quick and dirty ruby benchmark using benchmark-ips:
```ruby
require 'benchmark/ips'
require "active_support/time"

Time.zone = "America/Los_Angeles"
time = Time.parse("2017-03-11 06:00:00")
as_time = Time.zone.parse("2017-03-11 06:00:00")

Benchmark.ips do |x|
  x.report("add one day") { time + 1.day }
  x.report("add one day with as") { as_time + 1.day }
  x.compare!
end

# Warming up --------------------------------------
# add one day             7.213k i/100ms
# add one day with as     3.191k i/100ms
# Calculating -------------------------------------
# add one day             75.552k (± 3.8%) i/s -    382.289k in   5.067551s
# add one day with as     33.272k (± 5.7%) i/s -    165.932k in   5.004206s

# Comparison:
# add one day:            75552.3 i/s
# add one day with as:    33272.4 i/s - 2.27x  slower
```

A quick and dirty elixir benchmark using benchee:
```elixir
time = Timex.to_datetime({{2017, 3, 11}, {6, 0, 0}}, "America/Los_Angeles")

Benchee.run(%{
  "add one day" => fn -> Timex.shift(time, days: 1) end
})

# Benchmarking add one day...

# Name                  ips        average  deviation         median
# add one day        7.94 K      126.01 μs    ±26.55%      113.00 μs
```

Using warmup of 2s and runtime of 5s on both; using 2017-03-11 06:00:00 to show that all cases handle shifting across DST correctly.

It seems that Timex.shift is 10x slower than plain ruby and 5x slower than active support.

I'm working on a library that needs to shift times a lot, and this seems to be my main bottleneck. Is there anything we can do to speed up the shifting of datetimes?

**Comment by bitwalker** [comment]
Were you benchmarking Elixir with `MIX_ENV=prod` and protocols consolidated? If not, that would make a huge difference.

If that was all good, then while I suspect there are things we can do to improve the performance, the main reason things may be slow is that Timex ensures that shifts across timezones are done correctly, for any shift operation. We could optimize that for cases where the zone is "infinite", e.g. UTC which has no min or max bound, so we can easily determine shifts statically without having to look up the period for that zone. I don't have any control over the performance of the tzdata library either, so if that turns out to be a bottleneck, we would have to discuss it with the maintainer.

**Comment by sb8244** [comment]
I may end up looking into this if possible (non-committal now). I ran into this problem with an app where doing ~100k shifts would take over 15s. I changed it to use to_unix with manual seconds comparison for now, although I'm sure that's "incorrect" in the general use case; it is fine for mine.

I'll need to look at consolidating protocols and testing in prod ENV. I did all my testing in development env.

**Comment by doughsay** [comment]
For what it's worth, I discovered that most of the slowdown comes from timezone calculations.  Using `NaiveDateTime` instead of `DateTime` is much faster.

I've been working on a library that heavily utilizes shifts (https://github.com/peek-travel/cocktail), which is why I initially opened the issue, but having switched to naive times for my use-case, it's not as pressing of an issue right now with me either...

**Comment by bitwalker** [comment]
Yeah, unfortunately the calculation of shifts when involving timezones is non-trivial, and is rather poor performing due to the desire for accuracy. This is generally only an issue if doing tons of shifts in bulk, or in a tight loop, but as you've found, if you don't need to deal with timezone information, you can save a ton of time using NaiveDateTime. There are also less precise methods for doing shifts, which may work for some use cases, but Timex itself tries to be as accurate as possible.

**Comment by bitwalker** [comment]
There has been a lot of change here, I suspect this is no longer an issue, but am open to addressing futher perf issues if they are found!
