### ISSUE TITLE
inch-ci "doc coverage" doesn't seem to be updating

### ISSUE THREAD

**Issue by barbeque** [bitwalker/timex#373]
On the Inch-CI doc coverage [page for this repository](https://inch-ci.org/github/bitwalker/timex) it looks like it hasn't run in over a year.

Possibly the webhook has changed and needs to be updated from [their docs](https://inch-ci.org/help/webhook).

There may be other bugs or typos that the doc coverage exposes similar to the typo fixed in #372, and certainly a lot of functionality has been added since the last time it has run.

**Comment by bitwalker** [comment]
I just tried to update the webhook, but I'm getting a 500 from their servers, and it doesn't get much simpler than their docs (which themselves appear to be quite old). In any case, I haven't been using InchCI myself (or checking the dashboard for that matter). I actually removed the dependency a long time ago now, and didn't realize the webhook was still around. Since I don't really have time to maintain it, I've removed the webhook for now.

I don't disagree that it can be useful, but my preference is for tools which I can run as part of my build (or locally), and which don't rely on third-party services (unless there is significant value to be gained). With the limited amount of time I have to dedicate to my projects, I have to minimize the amount of extra tooling and administration required to maintain them or I would be continually swamped :(
