### ISSUE TITLE
`beginning_of_day/1` returns unexpected result

### ISSUE THREAD

**Issue by justuseapen** [bitwalker/timex#416]
### Steps to reproduce

- API function called
`beginning_of_day/1`
'end_of_day/1'

- Arguments provided
`Timex.today()`

### Description of issue

- What are the expected results?
I'd expect the function to return a datetime. Instead it just throws the date back. What would be the use of that? If there is a good reason I'd understand but I think it should probably return the same DateTime as if I passed in `Timex.now`

- If you are certain this is a bug in Timex, do you have references I
  can use to check the algorithm/logic against? For instance, a well-established
  date/time library in another language, a paper, test suite, etc. It is by no
  means a requirement, but is immensely helpful in fixing bugs, and provides me
  extra data to use when building out the test suite

No sorry. Just an intuition about good design.

If you decide the change is worth making I can take a crack at a PR.

**Comment by bitwalker** [comment]
A `Date` has no concept of a time associated with it, as such, `beginning_of_day` has no meaning. The Timex protocol does not perform conversions unless they are explicit, e.g. `to_datetime`, so if you feed the protocol a `Date`, you won't wind up with a different data type later. This is important because people do not want data types shifting underneath them once they have chosen one. Another problem is that if you are using Timex with a data type pulled from a database field (say via Ecto), you don't want manipulations via the Timex API to change the data type and then blow up when you try to save the data back because of type mismatches.

The choice between whether to implicitly convert or not is not a choice between "good" and "bad" design, it is a choice between tradeoffs, and in the spirit of how the Elixir community generally chooses to solve such problems, I prefer explicit conversions to implicit, and have made the tradeoffs based on that choice.
