### ISSUE TITLE
Invalid timezone when TZ env var not set

### ISSUE THREAD

**Issue by sleepiejohn** [bitwalker/timex#419]
### Environments

- Windows 10
	- Elixir 1.6.2
	- Erlang 20.2
	- Timex 3.2.1

- WSL Ubuntu 16
	- Elixir 1.6.2
	- Erlang 20.2
	- Timex 3.2.1

### Steps to reproduce

- `Timex.local/0`

### Description of issue

[Forum post](https://elixirforum.com/t/timex-seems-to-work-only-in-my-windows-environment-is-there-something-wrong-with-my-syntax/12933)

The problem starts on an OSX machine where it could not be able to reproduce the build from a Windows machine, at the Windows machine, `Timex.local/0` returns correctly using a timezone, on the OSX it fails with `{:error, {:unknown_timezone, "/etc/localtime"}}`. I was able to replicate on my WSL installation, making it plausible for a bug on *nix systems.

With further investigation, I found that we can ask the system about which timezone we are in since we need to configure when installing an OS. Using powershell on Windows issuing `[System.TimezoneInfo]::Local` returns the proper timezone for my machine. Search out for issues of unknown timezone, I stubbed on [this post](https://stackoverflow.com/questions/47314121/r-error-unknown-timezone-with-as-posixct), which made me try to lookup for the `TZ` env var, which I did not found on WSL, in the same instance of the shell I exported TZ as `/usr/share/zoneinfo/Brazil/East` and it failed again, setting it to `'America/Sao_Paulo'` fixed the issue and `Timex.local/0` executes correctly.

Seems it's a miss configuration on the OS, which might be out of scope for Timex, but in addition to the documentation would be nice alerting for the possible absence of `TZ`. All of that if there is no other way to fallback and the correct place to fetch such information is really `TZ` env var.

**Comment by bitwalker** [comment]
Timex doesn't expect `TZ` to be set, though it will respect the value if it is (as long as it is a valid timezone name). What it does is if `TZ` is not set, it checks `/etc/localtime`, which will be a zoneinfo file if the timezone is configured on the system. If that file does not exist, or can not be read due to permissions issues, then Timex will fail to find the local timezone information. Similar flows apply to all platforms, as there are a variety of paths used for timezone info, depending on the OS. It sounds to me like the macOS system you were testing with did not have the timezone configured at all. If you can reproduce, please provide me with the steps so that I can repro on my machine and investigate further.

Ultimately, Timex does require that the OS is configured with a timezone, but it does not place too many restrictions on _how_ you configure your timezone on the OS, as long as it is one of the well-known locations Timex checks.
