### ISSUE TITLE
Timex.parse returns badarg from ETS when tzdata application is not running.

### ISSUE THREAD

**Issue by electricshaman** [bitwalker/timex#431]
I think this is more of a developer experience issue than a bug.  

Elixir: `1.6.5`
Erlang/OTP: `20.3`
Timex: `3.3.0`

### Steps to reproduce

1. Run iex with `iex -S mix run --no-start`
2. Execute: `Timex.parse("Mon, 28 May 2018 13:00:02 EDT", "{WDshort}, {D} {Mfull} {YYYY} {h24}:{m}:{s} {Zabbr}")`

### Description of issue

It might not even be worth looking at, but I felt like I should report it since the developer is probably not expected to be aware of how `tzdata` is used under the hood.

If you fire up `iex` with `iex -S mix run --no-start` and then attempt to parse a date with directives using `Timex.parse`, it returns `{:error, :badarg}` from an ETS lookup that fails since `tzdata` isn't running.

### Expected result

Return an error tuple that is more revealing of the problem instead of returning the ETS lookup error tuple.  

### More context from `iex`

```elixir
iex(19)> Timex.parse("Mon, 28 May 2018 13:00:02 EDT", "{WDshort}, {D} {Mfull} {YYYY} {h24}:{m}:{s} {Zabbr}")
{:error, :badarg}
iex(20)> Timex.parse!("Mon, 28 May 2018 13:00:02 EDT", "{WDshort}, {D} {Mfull} {YYYY} {h24}:{m}:{s} {Zabbr}")
** (ArgumentError) argument error
    (stdlib) :ets.lookup(:tzdata_current_release, :release_version)
    lib/tzdata/release_reader.ex:47: Tzdata.ReleaseReader.current_release_from_table/0
    lib/tzdata/release_reader.ex:14: Tzdata.ReleaseReader.simple_lookup/1
    lib/tzdata/release_reader.ex:7: Tzdata.ReleaseReader.zone_and_link_list/0
    lib/tzdata.ex:40: Tzdata.zone_exists?/1
    lib/timezone/timezone.ex:152: Timex.Timezone.name_of/1
    lib/parse/datetime/parser.ex:408: Timex.Parse.DateTime.Parser.update_date/4
    lib/parse/datetime/parser.ex:208: Timex.Parse.DateTime.Parser.apply_directives/3
iex(20)> Application.ensure_all_started(:timex)
{:ok,
 [:idna, :mimerl, :certifi, :ssl_verify_fun, :metrics, :hackney, :tzdata,
  :gettext, :combine, :timex]}
iex(21)> Timex.parse!("Mon, 28 May 2018 13:00:02 EDT", "{WDshort}, {D} {Mfull} {YYYY} {h24}:{m}:{s} {Zabbr}")
#DateTime<2018-05-28 13:00:02-04:00 EDT EST5EDT>
```

**Comment by bitwalker** [comment]
This is expected behaviour if you run with `--no-start`, as no applications are started, so you can't expect them to work (they may, but that is incidental). You need to ensure you have started `:timex` or `:tzdata` (preferably the former, as it allows me to change deps and application requirements without you having to change your code). Timex won't make any attempt to verify this, as the tzdata requirement on an ETS table could change at some point (say if tzdata is compiled in rather than stored in ETS), that's why Timex declares `:tzdata` in it's dependencies and application list - it relies on being started like any other OTP application.
