### ISSUE TITLE
Cast Validation Error for optional date_select to DateTime

### ISSUE THREAD

**Issue by philippneugebauer** [bitwalker/timex#453]
I have a form with an optional date_select whose cast to DateTime fails with a cast validation error when the date is empty.
If the date_select has data entered, everything works fine. 
In contrast, an empty datetime_select works as well.

I believe that the behavior is inconsistent. Either it fails for every date_select/empty values or it works every time.

Unfortunately, I wasn't able to find the specific line to be fixed in Timex, but I located the call in TimexEcto: https://github.com/bitwalker/timex_ecto/blob/master/lib/types/datetime.ex#L90

What do you think?

**Comment by bitwalker** [comment]
Is this with Phoenix? If you can give me a repro case against `timex_ecto` which shows the empty date vs empty datetime discrepancy, I can make sure it is addressed there. This isn't a Timex issue though, the issue is that an Ecto changeset is being created to cast/validate options, and the cast via Timex fails because it really is an invalid date/time. The thing that catches my eye is that you mention it works with one data type, but not another, so I do want to address that.

**Comment by philippneugebauer** [comment]
yeah, it is. It took me a while to figure out, where the issue belongs to, but I believe now, you're right, it's related to `timex_ecto`.

here is my example: https://github.com/philippneugebauer/phoenix_html_date_select_error
