### ISSUE TITLE
Timex.Timezone.resolve returns an error when time does not exist in given timezone

### ISSUE THREAD

**Issue by mkorszun** [bitwalker/timex#475]
### Steps to reproduce

- API function called: `Timex.Timezone.resolve/2`
- Arguments provided: `["America/Moncton", {{2001, 4, 1}, {0, 3, 24}}]`
- Version: `3.4.1`

### Description of issue

- What are the expected results?
The target time - `2001-04-01T00:03:24-03:00` does not exist in given timezone. Still would expect `Timex.Timezone.resolve/2` to return corresponding / nearest time in given timezone, which would be `2001-04-01T01:03:24-03:00`
- Actual results
~~~
iex(7)> Timex.Timezone.resolve("America/Moncton", {{2001, 4, 1}, {0, 3, 24}})
{:error, {:could_not_resolve_timezone, "America/Moncton", 63153302604, :wall}}
~~~
- Similar logic with [`moment.js`](https://momentjs.com/)

~~~
$ npm install moment-timezone
$ node
> var moment = require('moment-timezone');
> moment.tz("2001-04-01 00:03:24", "America/Moncton").format()
'2001-04-01T01:03:24-03:00'
~~~

**Comment by bitwalker** [comment]
Just an FYI, but that API is private, and has been removed (it still exists in some form for gregorian seconds, but not for date/time tuples).

I don't agree that Timex APIs should return something other than exactly what is requested, except in some very few cases where it is expected that some variation may occur. In this example, you are asking for a particular date/time in some time zone - that date/time is not valid for that time zone, and we have no additional context with which to make a decision about how to deal with that, so the caller must do so.

**However**, with the changes in master, if you hit a date/time which doesn't exist during a shift, the shift _will_ do the right thing and move to the next valid time on the clock for that zone, but this can only be done because in the context of the shift, we know how to deal with the error without user intervention.
