### ISSUE TITLE
Numerical Imprecision on Timex.Duration.from_milliseconds/1

### ISSUE THREAD

**Issue by kasparinho** [bitwalker/timex#525]
### Steps to reproduce

iex> Timex.Duration.from_milliseconds(7261543)
#<Duration(PT2H1M1.5430000000000001S)>
iex> Timex.Duration.from_milliseconds(261543)
#<Duration(PT4M21.543S)>

### Description of issue

As the input is integer, i would expect the numerically precise result

iex> Timex.Duration.from_milliseconds(7261543)
#<Duration(PT2H1M1.543S)>

Where does the numerical imprecision come from? Is this a bug?

**Comment by bitwalker** [comment]
This is due to floating point math, the larger value results in a division at some point that isn't clean, hence the (incorrect) higher precision in that case. The "real" result is the lower precision value of 1.543. There isn't much we can do about this, without intentionally rounding to some max precision in all cases, which means that there may be cases where higher precision values lose some precision. That may be fine, since precision beyond nanoseconds is rather meaningless anyway, but I'm not sure there is one truly correct choice here, since I haven't explored all the possible edge cases.
