### ISSUE TITLE
How to get accurate timezoneInfo

### ISSUE THREAD

**Issue by mojidabckuu** [bitwalker/timex#539]
### Steps to reproduce

- Timex.Timezone.resolve("Asia/Dubai", 0, :utc).offset_utc
13272

- secs = Timex.to_gregorian_seconds(date)
63728639629
- Timex.Timezone.resolve("Asia/Dubai", secs, :utc).offset_utc
14400

### Description of issue

My issue is more question than real bug. The idea is to get the offset by given timezone using abbreviation. The docs in Timex.Timezone module doesn't explain necessity of secs and there is no any other function like `Timex.TimezoneInfo.from_abbr("Asia/Dubai")` So if I pass 
`Timex.Timezone.resolve("Asia/Dubai", 0, :utc).offset_utc` the result is `13272`. Seems it requires to pass the current date to get the expected result. Is there any way to omit this and just get latest fresh time offset by timezone name/abbr?

**Comment by bitwalker** [comment]
This seems like something you may want to use `tzdata` directly for, but could you describe more what the use case is here? There should be very few things that don't already have higher-level APIs around timezones, such as converting a DateTime from one timezone to another, constructing a DateTime in some timezone, etc.

**Comment by mojidabckuu** [comment]
I am looking for functionality to get accurate time offset by timezone name abbreviation.

**Comment by bitwalker** [comment]
Right, but what I mean is what are you doing with the offset - those offsets are specific to a date and time, they aren't reusable for multiple date/times and don't really make sense independently. If you are trying to convert a date/time from one timezone to another, then you can do that with the higher-level APIs, rather than doing so manually with an offset (which is extremely error prone).

In any case, if you truly need that kind of low-level functionality, then you'll want to use `tzdata` for that, as it is designed for that type of use. Since you are already pulling in `timex`, `tzdata` is a dependency, and available to you, but you'll need to read the [docs](https://hexdocs.pm/tzdata) to figure out what combination of APIs you need.

**Comment by mojidabckuu** [comment]
What I like in Elixir community is that everybody who is in main contributor list treats people with care :)

Sorry, it was better to ask this question in tzdata dep.
The point was to get an offset to build a DateTime object on client. After reading the doc I missed the fact that it takes DST into scope. So now I understand the necessity of current date.
