### ISSUE TITLE
Ambiguous times not detected any more while resolving to a timezone

### ISSUE THREAD

**Issue by mkorszun** [bitwalker/timex#548]
### Steps to reproduce

- API function called: `Timex.Timezone.resolve/2`
- Arguments provided:
~~~elixir
[~N[2018-11-04T06:00:00], "America/New_York"]
~~~
- Version: `3.6.1`

### Description of issue

- What are the expected results (works in `3.5.0`)?
The input UTC time `2018-11-04T06:00:00` should resolve to ambiguous times:
  * `2018-11-04 02:00:00-04:00 EDT America/New_York`
  * `2018-11-04 01:00:00-05:00 EST America/New_York`

~~~elixir
iex(10)> ~N[2018-11-04T06:00:00] |> Timex.Timezone.convert("America/New_York")
#<Ambiguous(#DateTime<2018-11-04 02:00:00-04:00 EDT America/New_York> ~ #DateTime<2018-11-04 01:00:00-05:00 EST America/New_York>)>
~~~

My understanding is that there is `EDT` -> `EST` shift (end of [DST](https://www.timeanddate.com/time/change/usa?year=2018)), which happens at `2018-11-04 02:00 America/New_York`, where time is shifted from `02:00` -> `01:00`.
This means that such a local time (`02:00:00`) is represented in two different time zones: `EDT` and `EST`.

- Actual results:

~~~elixir
iex(2)> ~N[2018-11-04T06:00:00] |> Timex.Timezone.convert("America/New_York")
#DateTime<2018-11-04 02:00:00-04:00 EDT America/New_York>
~~~

So, looks like ambiguity is auto resolved, to `previous` moment. Of course I might be completely wrong here, since this is super confusing topic but at least would like to understand why this behavior has changed.

**Comment by bitwalker** [comment]
As of 3.7, the behavior of converting a NaiveDateTime via `Timex.Timezone` is to treat the NaiveDateTime as the desired time in the specified zone, whereas before it was assuming the NaiveDateTIme was in UTC. If you have a UTC date/time and convert it, then it will be shifted appropriately.

Using the date/time you've provided here as a UTC date/time:

```elixir
~U[2018-11-04T06:00:00Z] |> Timex.Timezone.convert("America/New_York")
> #DateTime<2018-11-04 01:00:00-05:00 EST America/New_York>
```

The behavior here is correct because the 1AM hour is repeated twice, the second time due to the clock "falling back". If you take a spring date, such as this years DST change, converting from UTC to `America/New_York` is unambiguous, again because the clock "skips" an hour. However, if you try to cast a NaiveDateTime, you get an ambiguous date/time as you'd expect:

```elixir
iex> ~N[2021-03-14T02:15:00] |> Timex.Timezone.convert("America/New_York")
#<Gap(#DateTime<2021-03-14 01:59:59.999999-05:00 EST America/New_York> ~ #DateTime<2021-03-14 03:00:00-04:00 EDT America/New_York>)>
```
