### ISSUE TITLE
Wrong time difference count (granularity: months) 

### ISSUE THREAD

**Issue by kpietkaa** [bitwalker/timex#554]
Timex version:  `3.6.1`
### Steps to reproduce
```elixir
date_in_past =
        Timex.to_datetime(~D[2019-08-03])
        |> Timex.shift(hours: 2)

time_now = Timex.to_datetime(~D[2019-09-03])
```
#### Received
```elixir
> Timex.diff(time_now, date_in_past, :months)
1
```

#### Expected
```elixir
> Timex.diff(time_now, date_in_past, :months)
0
```

When I count the difference in hours:

``` elixir
> diff_in_hours = Timex.diff(time_now, date_in_past, :hours)
742

> diff_in_hours / 24
30.916666666666668
```
So the month has not passed but with (granularity: months) Timex says that month has passed.

**Comment by MariliaMJ** [comment]
hi @kpietkaa !
Let me see if I got this straight:
1) You have a date in the past `#DateTime<2019-08-03 02:00:00Z>`, which is 
August 3rd, 2019, at 2 am.
2) You added a recent date, which is `#DateTime<2019-09-03 00:00:00Z>`, which is September 3rd, at midnight, also in the year 2019;
3) You took the difference between those two and the result is `1`, and you expected it to be 0, right?

I assume that the answer provided by the diff function is correct,  there is indeed 30 days between those dates.
What I infer here is that you thought that the `3` in the both dates was the month and not the day, which then would make sense.
If you run: 
```
date_in_past = Timex.to_datetime(~D[2019-08-03]) |> Timex.shift(hours: 2)
#DateTime<2019-08-03 02:00:00Z>
time_now = Timex.to_datetime(~D[2019-08-03]) 
#DateTime<2019-08-03 00:00:00Z>
> Timex.diff(time_now, date_in_past, :days)   
0
> Timex.diff(time_now, date_in_past, :months)
0
```
It is the result you expected, but note that now both dates are in the same month.

Please let me know if I understood your problem correctly!

**Comment by kpietkaa** [comment]
Hey @MariliaMJ !

Thanks for the response. I will try to explain it as clear as I can :smile: 
You got me right here:

> 1. You have a date in the past `#DateTime<2019-08-03 02:00:00Z>`, which is
>    August 3rd, 2019, at 2 am.
> 2. You added a recent date, which is `#DateTime<2019-09-03 00:00:00Z>`, which is September 3rd, at midnight, also in the year 2019;
> 3. You took the difference between those two and the result is `1`, and you expected it to be 0, right?

I get 0 when date in the past is:

```elixir
date_in_past = Timex.to_datetime(~D[2019-08-03]) |> Timex.shift(hours: 24)
#DateTime<2019-08-04 00:00:00Z>

time_now = Timex.to_datetime(~D[2019-09-03])
#DateTime<2019-09-03 00:00:00Z>

Timex.diff(time_now, date_in_past, :months)
0
```

So, Timex gets difference in months wrong when comparing two dates with the same day of the month but different time of the day. I get 0 when I shift the date by whole day (24 hours) but 1 when the date is shifted by 23 hours. I think `Timex.diff` it should take hours into account as well.

**Comment by bitwalker** [comment]
Diffing in months (and years) is not quite like other units, as it is inherently inprecise due to its relatively loose definition, i.e. does a month have 28/29/30/31 days, does the start and end span multiple months (and so need to account for the variances in those months). In general, it is not intended to be used in contexts where high precision is required.

Because of that, Timex does not attempt to be perfectly precise with months, it does not factor in the time component at all because the inherent lack of precision allows for variance of up to a day, and even if we did factor it in, it would simply add additional unpredictablity to the results. Timex instead diffs two dates using their year/month/day components, taking the difference in years/months as the base difference, with some additional handling for edge cases when the start/end dates occur in the 29-31st days of their respective months.

The docs do indicate that the granularity corresponds to the accuracy, but could perhaps be clarified to say exactly how precise they are intended to be. Years/months/weeks are accurate to within a day; days are accurate to within an hour; and so on.
