### ISSUE TITLE
Not clear what locales are supported and how to extend with my own

### ISSUE THREAD

**Issue by revati** [bitwalker/timex#557]
1. Documentation has multiple places mentioning `only for the locales in the list of supported locales in the Timex documentation` (https://hexdocs.pm/timex/Timex.html#lformat/4), but list it self I couldn't find. The only place where I can see supported locales are going to `deps/timex/priv/translations` directory.
2. If I need to translate it for not supported language (maybe later I will create PR for it, but now I just need to make it work) what is the workflow for that? Should I just copy manually `.pot` files to my `priv/gettext` folder?

**Comment by bitwalker** [comment]
To build new translations, it is necessary to clone Timex and build the translations in the Timex repo, you can then open a PR with the translation to get them merged (if it's an official language, or one that makes sense for us to add due to common use). If you want to use your custom translations separate from Timex, you'd need to fork Timex at the moment, as there is no facility to plug in your own translations from outside Timex. This is something that could in theory be supported, but hasn't been worth the effort it would take to refactor in that support.

I don't maintain an official list of translations currently as the most up to date source is the list found in `priv/translations`, and I haven't had time to put one together. A PR is certainly welcome!
