### ISSUE TITLE
How to get the Timezone offset nicely formatted as a String

### ISSUE THREAD

**Issue by egeersoz** [bitwalker/timex#558]
This is more of a question. I checked the documentation on both Timex and Timex.Timezone, played with various functions in IEX and couldn't figure it out.

In `moment.js`, which is the most popular JavaScript Date/Time library out there, I can do this:

```
> moment().format("Z")
> "-05:00"
```

Basically, it is a way to get a nicely formatted String that represents the offset of the given datetime's timezone. More info here: https://momentjs.com/docs/#/displaying/format/

Does anyone know the equivalent for Timex? I want to say "get the offset for timezone X on date Y" and have it spit out an _identically_ formatted String.

I tried this, but the best I could get is a Decimal:

```
iex> Timex.Timezone.get("America/Chicago", Timex.now())
#<TimezoneInfo(America/Chicago - CDT (-05:00:00))>

iex> (Timex.Timezone.get("America/Chicago", Timex.now()) |> Timex.Timezone.total_offset) / 3600)
-5.0
```

I'm trying to avoid writing my own Decimal to String formatter if one already exists in Timex.

**Comment by ckhrysze** [comment]
If I understand what you want correctly, this can be done with:

```
Timex.now("America/Chicago") |> Timex.format!("{Z:}")
```
The various options to format for the default formatter can be found at: https://hexdocs.pm/timex/Timex.Format.DateTime.Formatters.Default.html

More than happy to dig in more if needed, so please re-open or ping me if I missed something. Closing mainly because I think you are more likely to be alerted if I do.
