### ISSUE TITLE
Help with formatting a time stamp? 

### ISSUE THREAD

**Issue by vsmart** [bitwalker/timex#56]
Hi, 
How would I go about creating an ISOz timestamp without miliseconds from the current time? (like this: ` 2015-06-24T05:04:13Z`).
You give this example in the readme:
```> Date.local |> DateFormat.format("{ISOz}")
{:ok, "2015-06-24T05:04:13.910Z"}```
In your tests I saw [this line](https://github.com/bitwalker/timex/blob/master/test/format_default_test.exs#L228) which is essentially what I want, but that is given a time w/o ms. 

Do I need to round or preformat `Date.local` first? 

Hope this is clear, Thank you for any suggestions.

**Comment by bitwalker** [comment]
You'll have to use the individual tokens, so in this case it would be:

```elixir
Date.local |> Timezone.convert("UTC") |> DateFormat.format("{ISOdate}T{0h24}:{0m}:{0s}Z")
```

This effectively duplicates what the `{ISOz}` shortcut directive does, but does not print fractional seconds. `{ISOz}` expands to `{ISOdate}T{ISOtime}Z`, which expands to `{000YYYY}-{0M}-{0D}T{{0h24}:{0m}:{0s}{ss}Z`, in case your curious what the formats are. The reason why `{ISOz}` does implicit conversion to UTC (along with other z-suffixed directives like `{RFC1123z}`) is due to some special case handling I do inside the parser for those.

**Comment by vsmart** [comment]
Great. Thank you!
