### ISSUE TITLE
No timezone found for: EDT

### ISSUE THREAD

**Issue by b0oh** [bitwalker/timex#57]
When I am trying to parse date like that: `"Mon, 02 Mar 2015 06:48:00 EDT"` I am getting an error:
```
> {:ok, date} = Timex.DateFormat.parse("Mon, 02 Mar 2015 06:48:00 EDT", "{RFC1123}") 
{:ok,
 %Timex.DateTime{calendar: :gregorian, day: 2, hour: 6, minute: 48, month: 3,
  ms: 0, second: 0, timezone: {:error, "No timezone found for: EDT"},
  year: 2015}}
> Timex.Date.universal(date)
** (MatchError) no match of right hand side value: {:error, "No timezone found for: EDT"}
    lib/timezone/timezone.ex:147: Timex.Timezone.diff/2
    lib/timezone/timezone.ex:128: Timex.Timezone.convert/2
```

I opened an [issue](/lau/tzdata/issues/3) in Tzdata, but I am not sure if it is their issue.

**Comment by bitwalker** [comment]
@b0oh the problem is that there is no timezone with the abbreviation "EDT" for the date specified. Timezones are date/time sensitive, so while you can hack around Timex to assign an invalid timezone to a DateTime, it won't let you using the API.

To see why it fails, observe what I get running `Timezone.get("EDT")`:

```elixir
%Timex.TimezoneInfo{abbreviation: "EDT",
 from: {:sunday, {{2015, 3, 8}, {2, 0, 0}}}, full_name: "America/Detroit",
 offset_std: 60, offset_utc: -300, until: {:sunday, {{2015, 11, 1}, {1, 0, 0}}}}
```

As you can see, EDT started on March 8th (expected), and your date falls before that.
