### ISSUE TITLE
Timex.equal?(%NaiveDateTime{}, %Date{}, :day) returns true for dates that are not equal

### ISSUE THREAD

**Issue by ckruse** [bitwalker/timex#602]
### Steps to reproduce

~~~
Timex.equal?(~N[2020-04-09 14:25:57], ~D[2020-04-10])
# false
Timex.equal?(~N[2020-04-09 14:25:57], ~D[2020-04-10], :day)
# true
Timex.equal?(~N[2020-04-09 14:25:57] |> Timex.to_date, ~D[2020-04-10], :day)
# false
Timex.equal?(~N[2020-04-09 14:25:57], ~D[2020-04-10] |> Timex.to_naive_datetime, :day)
# true
Timex.equal?(~N[2020-04-08 14:25:57], ~D[2020-04-10], :day)
# false
~~~

### Description of issue

The days of the NaiveDateTime and the date are differing, `Timex.equal?(..., :day)` should return false. I guess this is a time zone issue? `Timex.compare()` seems to suffer from the same issue:

~~~
Timex.compare(~N[2020-04-09 14:25:57], ~D[2020-04-10])
-1
Timex.compare(~N[2020-04-09 14:25:57], ~D[2020-04-10], :day)
# 0
~~~

**Comment by pedroperrone** [comment]
Hey all,
@seidelmaycon and I digged into this issue and we've noticed the following:
When we call `Timex.equal?(~N[2020-04-09 14:25:57], ~D[2020-04-10], :day)`, it calls the function `Timex.compare/2`. This second function calls the `DateTime` implementation for the `Timex.Comparable` protocol. This implementation calls the `Timex.Comparable.Diff.diff/3` function.

In the end, the `Timex.equal?/3` returns true if the difference between the dates is zero and false otherwise. In your example, **the difference between the NaiveDateTime and the Date is smaller than 24 hours and the diff function says that their difference is smaller than a day.** With the difference in days being 0, the `Timex.equal?/3` function says they are the same day.

**Comment by seidelmaycon** [comment]
`Timex.Comparable.Diff.diff/3` calls an internal function `do_diff/3` by PM with `:day`. We changed

`div(a - b, 1_000 * 1_000 * 60 * 60 * 24)`
for
`div(a, @microseconds_in_a_day) - div(b, @microseconds_in_a_day)`

This way we'd treat days as "packages" of 24 hours and return the difference of days between both.
That would work for `equal?/3` function, but, unfortunately, it changes the semantics of the `diff` function, which breaks the API of the library and the behavior of other functions like `format/3` when asking for a *dord* format.

We believe that to solve this problem the `equal/3` function should be completely reformulated to not use the existent `Timex.Comparable.Diff` module.

**Comment by bitwalker** [comment]
The docs are pretty explicit that equality is based on the granularity of comparison of the two input values - if the granularity is in days and the difference is less than a day, then they can be considered equal. 

I think the issue here is that you are expecting the granularity to apply to the value of the day field in the date/time, because in the specific context here (Naive vs Date), that is intuitive. Timex doesn't do context-sensitive comparisons though, primarily to avoid unpredictable behavior, and instead reduces all comparisons down in terms of absolute time difference. The granularity is how we determine whether that time difference is significant for a comparison (i.e. if the difference is less than one unit of the granularity specified, then the difference is considered insignificant). This is of primary importance when comparing DateTime values, as they can be in different zones and the only way to reason about them is in terms of absolute time, but obviously there are cases like yours where it feels strange.

A more complex solution would take into account the types of the arguments and reason about what the intent of the comparison is, but that quickly gets difficult to explain and the behavior might feel unpredictable. At the very least, the uniform approach Timex currently uses has neither of those issues, though it may feel strange at first. If you think there are better ways to document this, I'm always open to feedback on how to improve the documentation.
