### ISSUE TITLE
Durations with the same representation are not equivalent

### ISSUE THREAD

**Issue by axelson** [bitwalker/timex#603]
### Steps to reproduce

Based on my understanding of the Timex.Duration module, I would expect all three of these tests to pass, but instead only the third one passes:

```elixir
  test "timex duration broken 1" do
    duration_str = "PT13M39.999S"
    duration1 = Timex.Duration.parse!(duration_str)

    duration2 =
      Timex.Duration.parse!("PT13M40S")
      |> Timex.Duration.sub(Timex.Duration.from_milliseconds(1))

    assert Timex.Duration.to_string(duration1) == Timex.Duration.to_string(duration2)

    assert Timex.Duration.to_clock(duration1) == Timex.Duration.to_clock(duration2)
  end

  test "timex duration broken 2" do
    duration_str = "PT13M39.999S"
    duration1 = Timex.Duration.parse!(duration_str)

    duration2 =
      Timex.Duration.parse!("PT13M40S")
      |> Timex.Duration.sub(Timex.Duration.from_milliseconds(1))
      |> Timex.Duration.normalize()

    assert Timex.Duration.to_string(duration1) == Timex.Duration.to_string(duration2)

    assert Timex.Duration.to_clock(duration1) == Timex.Duration.to_clock(duration2)
  end

  test "timex duration works" do
    duration_str = "PT13M39.999S"
    duration1 = Timex.Duration.parse!(duration_str)

    duration2 =
      Timex.Duration.parse!("PT13M40S")
      |> Timex.Duration.sub(Timex.Duration.from_milliseconds(1))
      |> Timex.Duration.to_string()
      |> Timex.Duration.parse!()

    assert Timex.Duration.to_string(duration1) == Timex.Duration.to_string(duration2)

    assert Timex.Duration.to_clock(duration1) == Timex.Duration.to_clock(duration2)
  end
```
### Description of issue

I expect all three tests to pass.

Is that correct and can this be considered a bug? Should this be something that `normalize` should handle? There's no doc for normalize so it's a little hard to tell.

**Comment by bitwalker** [comment]
The underlying representation of the Duration can have different values for seconds and microseconds, depending on how the Duration was constructed/arrived at. 

The first test doesn't normalize the duration, so it has different values for seconds/microseconds.

The second test only normalizes one of them.

The third test "normalizes" by round-tripping through the string representation, but that only works because both durations were parsed from the same string.

You must use `normalize/1` on both values if you want them to be equivalent. That said, I think for purposes of `to_clock/1`, we can call `normalize/1` internally, since normalizing the representation for the clock output makes sense. I'll add that and release in 3.7.2

**Comment by axelson** [comment]
Great, thanks :+1:
