### ISSUE TITLE
ArgumentError when using as default value struct

### ISSUE THREAD

**Issue by Ajwah** [bitwalker/timex#609]
Compilation time I receive following error:
```bash
** (ArgumentError) argument error
    (stdlib 3.12.1) :ets.lookup(:tzdata_current_release, :release_version)
    lib/tzdata/release_reader.ex:74: Tzdata.ReleaseReader.current_release_from_table/0
    lib/tzdata/release_reader.ex:17: Tzdata.ReleaseReader.simple_lookup/1
    lib/tzdata/release_reader.ex:9: Tzdata.ReleaseReader.zone_and_link_list/0
    lib/tzdata.ex:61: Tzdata.zone_exists?/1
    lib/timezone/timezone.ex:28: Timex.Timezone.exists?/1
```

The reason for this is because the ets-table does not exist at compile time.
This in general makes sense as the concept of time is a runtime concept; not a compile time concept.

My use case is that I have the practice of setting default values for my structs so:
1. Documentation-wise it is easy to see what they concretely represent inside `IEx`
2. Validation-wise, I have my own macros that expand as a `with` statement compilation time using the default values that I provide in my struct to see if the input I receive is of the same type as what is supposed to be covered under the definition of the struct.

Next, I have no viable alternative by for instance creating a `DateTime` struct manually as my structs tend to be composable where they can be nested structs where I would be referring to the child struct compile time as: `Child.new()`
which in turn contains the Timex functions that rely on the ets table.

### Steps to reproduce

The easiest way to reproduce:
```elixir
defmodule A do
  defstruct [
    a: [Timex.to_datetime({2015, 1, 1}, "America/Toronto")]
  ]
end
```

- API function called: `Timex.to_datetime/2`
- Arguments provided: `{2015, 1, 1}` and  `"America/Toronto"`

### Description of issue

- What are the expected results?
Compilation time, a default value is set:
```elixir
%A{a: [#DateTime<2015-01-01 00:00:00-05:00 EST America/Toronto>]}
```

- If you are certain this is a bug in Timex, do you have references I
  can use to check the algorithm/logic against? For instance, a well-established
  date/time library in another language, a paper, test suite, etc. It is by no
  means a requirement, but is immensely helpful in fixing bugs, and provides me
  extra data to use when building out the test suite

I am not claiming that this is a bug per se. I hope that some solution can be formulated for my use case.

**Comment by bitwalker** [comment]
The solution here is to start `:tzdata` during compilation - there isn't any way around that I'm afraid, `tzdata` is our source for time zone information, and without it, your use of `to_datetime` there would fail due to lack of that information.

As a general rule this is a bad idea anyway though, as `tzdata` can update the timezone database at any time, and the rules for a particular zone could change from underneath you - if you compile in the version of a zone that gets changed, you may observe strange issues depending on use. If you must compile in a DateTime, then you should do so in UTC and convert to a desired zone at runtime to ensure you always get a date/time with the latest timezone info.
