### ISSUE TITLE
Timex#to_naive_datetime/1 converts to UTC before creating a Naive Datetime

### ISSUE THREAD

**Issue by nicolasblanco** [bitwalker/timex#613]
Hello,

I've just noticed that `Timex#to_naive_datetime/1` converts the DateTime with a specific timezone to UTC before giving back a Naive DateTime.

Is this behaviour correct? If this behaviour is correct, I think this should be documented in the function documentation.
I can create a small PR to add this behaviour in the function documentation.
I originally expected the behaviour to just lose the time zone information before giving back a Naive DateTime.

Thanks!

**Comment by bitwalker** [comment]
This is something I intend to align with the standard library on, but due to backwards compatibility reasons I've left the legacy behaviour. The original intent way back was to try and make naive datetimes align with how people typically think about them (i.e. as a generalization, it was my observation that many people tend to assume that date/times without a timezone are UTC). In any case, the standard library behavior is more correct in this regard, so with Timex 4 I plan to break backwards compatibility there, barring significant pushback from users.

A PR improving the docs is always welcome!
