### ISSUE TITLE
Timex.compare/3 Not Returning as Expected

### ISSUE THREAD

**Issue by JasonForsey** [bitwalker/timex#666]
Not overly sure if this is an issue or maybe just a document issue. I am following the documentation on this page:
https://hexdocs.pm/timex/Timex.html#compare/3

From reading the above I was under the impression that adding a granularity level of :day would differentiate between two differing calendar days.

### Steps to reproduce
Using version 3.6.4

- Timex.compare/3
- ~U[2021-04-27 23:59:59Z], ~U[2021-04-28 14:00:00Z], :day

### Description of issue

- What are the expected results?
I am expecting the above comparison return a value of -1 as the first date is an earlier "day" than the second date passed.
- What's happening instead?
The comparison is returning 0. I believe this is because a full 24 hours hasn't passed as when I change the second date above to be ~U[2021-04-28 23:59:59Z] the comparison returns -1 as expected. I have gotten round this issue by wrapping each of the dates in Timex.end_of_day/1 however, thought I would raise an issue in case it's either something that needs to be addressed in the documentation or the comparison code itself.

**Comment by bitwalker** [comment]
I've updated the documentation for `compare` to clarify what the granularity of `days` and `weeks` means in the context of the API. This is expected behavior, since the naive approach of just comparing the day number (e.g. `27`) is insufficient for some edge cases involving timezone shifts. Unfortunately, the trade off is that it's not particularly intuitive. Your solution of using `end_of_day` is a good approach to normalize the date/times to produce a more intuitive result.
