### ISSUE TITLE
Timezone abbreviations no longer parsed with `Timex.Timezone.get/2`

### ISSUE THREAD

**Issue by dbernheisel** [bitwalker/timex#673]
### Steps to reproduce

In Timex v3.7.2

```elixir
iex(1)> Timex.Timezone.get("PST", ~N[2021-01-01T00:00:00])
#<TimezoneInfo(PST8PDT - PST (-08:00:00))>
iex(2)> Timex.Timezone.get("PST", ~N[2021-05-01T00:00:00])
#<TimezoneInfo(PST8PDT - PDT (-07:00:00))>
```

In Timex v3.7.3

```elixir
iex(1)> Timex.Timezone.get("PST", ~N[2021-01-01T00:00:00])
{:error, :time_zone_not_found}
iex(2)> Timex.Timezone.get("PST", ~N[2021-05-01T00:00:00])
{:error, :time_zone_not_found}
```

### Description of issue

- The POSIX timezones now require the full name, "PDT8PST" or "PST8PDT" in order to parse successfully and no longer works with the abbreviation.
- [This commit seems to be the regression](https://github.com/bitwalker/timex/commit/91cd0ed9daf5237cc2973d3625576fdd0e3cb12e)

**Comment by bitwalker** [comment]
Support for invalid Olson/POSIX timezone names was always explicitly a non-goal in Timex, it was actually improperly implemented POSIX timezone parsing that even allowed this to work at all. Specifically, it is impossible for Timex to do anything properly with a timezone name like `PST` - it doesn't contain enough information to determine anything about it. There _are_ some POSIX compatibility zones in the Olson database, namely `PST8PDT`, `EST`, `CST6CDT`, and `MST`, and all of those work with Timex as expected, but Timex does not, and was never intended, to support POSIX abbrevations as timezone names. You must use either the Olson compat zones, or use a valid POSIX timezone string.

I apologize if this has caused any issues on your end, I've explicitly warned in the docs against using non-Olson names for this reason, but either due to bugs or undocumented behavior, things like this do break. I generally do not do major version bumps for changes to undocumented APIs or behavior, unless it is something that is likely to cause widespread breakage without a deprecation cycle.
