### ISSUE TITLE
Not working in exrm release

### ISSUE THREAD

**Issue by ftaebi** [bitwalker/timex#73]
Hi, 
I'm using Timex 0.19.2 and it works as expected. But ..., it does not work inside my exrm (0.19.2) releases. All I can say right now is that no Timex modules are available when I attach to the console. Fortunately U also maintain the exrm repo.

**Comment by ftaebi** [comment]
It works after putting timex under "applications". I didn't expect it to be necessary because it is not an application which has to be started before my application but only a bunch of functions.

**Comment by bitwalker** [comment]
@ftaebi There is common confusion around this with newcomers to the Erlang/Elixir languages, I've covered this in more detail in the exrm docs, but the basic explanation consists of two parts:

1. Applications in Erlang/Elixir consist of two types, those which start a supervision tree, and those which are just a collection of modules/functions. They are effectively the same thing even though coming from other languages/platforms, we wouldn't call the latter an application, that is what it's called in Erlang terms.
2. When a release is compiled, `applications` and `included_applications` are how the release packager knows what applications need to be included in the release. The difference between those is primarily that `included_applications` does not start the applications, whereas `applications` does, but it is not quite that clear cut. You can use `included_applications`, but keep in mind that only one application in the release can have any given application in `included_applications`, as it is implicit that your application is taking responsibility for starting the included application. I would recommend always putting dependent applications in `applications` rather than `included_applications`, unless you have good reason to use the latter.

Hopefully that clarifies things a bit, releases are a complex world, and exrm makes it so easy to get into that you tend to run into these things before the reasoning is made clear. If you have any suggestions for the exrm docs, issues in the exrm repo are always welcome for documentation :)

**Comment by ftaebi** [comment]
Thanks a lot for the clarification.
