### ISSUE TITLE
Can Timex parse a relative string into a DateTime?

### ISSUE THREAD

**Issue by sergiotapia** [bitwalker/timex#740]
I'm trying to parse a string from HTML that looks like: `"22 days ago"` into a proper DateTime object to persist in my database.

In Rail's land with [Chronic](https://github.com/mojombo/chronic) I can go: `Chronic.parse(string)` - is this something Timex can do today?

Thanks!

**Comment by bitwalker** [comment]
See [human_time](https://github.com/teifion/human_time) for a library built on Timex that provides this functionality. I'm not sure if it is built on top of Timex's parser/formatter extension points (I suspect not, since it appears to provide it's own higher-level API), but it does provide the functionality you are looking for.

It is also possible to implement this yourself by extending Timex with a custom parser, if you know/control the format, but we do not currently have an in-tree relative-time parser.
